Repository karnkaul/MicroEngine, pull requests merged in 2019-10, with the labels that each got.

#4 Merge dev
  .editorconfig
Labels: enhancement

#11 Merge Karnage/dev into dev
  .gitignore
  Source/Game/Engine/GFX.cpp
  Source/Game/Engine/GFX.h
  Source/Game/Engine/GameServices.cpp
  Source/Game/Engine/GameServices.h
  Source/Game/Engine/Input/Input.cpp
  Source/Game/Engine/Input/Input.h
  Source/Game/Engine/Viewport/Viewport.cpp
  Source/Game/Engine/Viewport/Viewport.h
  Source/Game/GameContext/GameContext.cpp
  Source/Game/GameContext/GameContext.h
  Source/Game/GameContext/Objects/GameObject.cpp
  Source/Game/GameContext/Objects/GameObject.h
  Source/Game/GameContext/Objects/Tutorials/Bubble.cpp
  Source/Game/GameContext/Objects/Tutorials/Bubble.h
  Source/Game/GameContext/Worlds/GameWorld.cpp
  Source/Game/GameContext/Worlds/GameWorld.h
  Source/Game/GameContext/Worlds/Tutorials/Temp.cpp
  Source/Game/GameContext/Worlds/Tutorials/Temp.h
  Source/Game/GameContext/Worlds/Tutorials/Tutorial0.cpp
  Source/Game/GameContext/Worlds/Tutorials/Tutorial1.cpp
  Source/Game/GameContext/Worlds/Tutorials/Tutorial2.cpp
  Source/Game/GameContext/Worlds/Tutorials/Tutorial3.cpp
  Source/Game/GameContext/Worlds/Tutorials/Tutorial3.h
  Source/Game/GameContext/Worlds/Worlds.h
  Source/Game/GameLoop/App.cpp
  Source/Game/GameLoop/App.h
  Source/Game/GameLoop/GameLoop.cpp
  Source/Game/GameLoop/GameLoop.h
  Source/Source.cmake
  Tools/build.sh
  Tools/clang-format.sh
  Tools/os.sh
Labels: enhancement

#15 `Tutorial3`: Explicitly load `Tutorial2`
  Source/Game/GameContext/Worlds/Tutorials/Tutorial3.cpp
Labels: bug

#20 Tools: Add "clean.sh"
  Tools/clean.sh
Labels: enhancement

#22 Update issue and pull request templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
Labels: documentation

#24 * Implemented 4 ColliderData algorithms
  Source/Game/Engine/Physics/ColliderData.cpp
Labels: enhancement

#26 BUGFIX: Process all colliders
  Source/Game/Engine/Physics/Physics.cpp
Labels: bug
